name: 'build'

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  Codacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Version
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
      - name: Build & Test
        run: |
          dotnet build
          cd Cheerful.Test
          dotnet test --collect:"XPlat Code Coverage"
          ls
          find ./Cheerful.Test/*TestResults* -name "*coverage*.xml" -type f -exec cp {} ./ \;
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          api-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: 'coverage.cobertura.xml'
