name: 'release'

on:
  release:

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - name: checks-out repository
        uses: actions/checkout@v3
      - name: Setup .NET Version
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
      - name: Build
        run: |
          dotnet build
      - name: debug
        run: |
          VERSION=`git describe --tags`
          echo "Publishing Version: ${VERSION}"

#      - name: push & Nuget

#dotnet nuget push Cheerful.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }}
