name: 'release'

on:
  release:
    types: [published]

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - name: checks-out repository
        uses: actions/checkout@v3
      - name: Setup .NET Version
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
      - name: Build
        run: |
          dotnet build
      - name: debug
        run: |
          VERSION=`git describe --tags`
          echo "Publishing Version: ${VERSION}"
          dotnet build
          ls
          dotnet pack Cheerful.csproj /p:PackageVersion=$VERSION /p:ContinuousIntegrationBuild=true -c Release -o publish
          dotnet nuget push 'publish/*.nupkg' -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

#      - name: push & Nuget

#dotnet nuget push Cheerful.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }}
