name: 'release'

on:
  release:

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - name: checks-out repository
        uses: actions/checkout@v3
      - name: Setup .NET Version
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
      - name: Build
        run: |
          dotnet build
      - name: push & Nuget
        run: |
          dotnet nuget push Cheerful.1.0.0.nupkg --api-key qz2jga8pl3dvn2akksyquwcs9ygggg4exypy3bhxy6w6x6 --source https://api.nuget.org/v3/index.json
